apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: conference-app

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - monitoring.yaml

commonLabels:
  project: conference-app
  version: v1.0.0

images:
  - name: conference-backend
    newTag: latest
  - name: conference-frontend
    newTag: latest