apiVersion: v1
kind: Secret
metadata:
  name: conference-secrets
  namespace: conference-app
type: Opaque
data:
  # Base64 encoded values
  # conference_pass = Y29uZmVyZW5jZV9wYXNz
  # admin = YWRtaW4=
  POSTGRES_PASSWORD: Y29uZmVyZW5jZV9wYXNz
  GF_SECURITY_ADMIN_PASSWORD: YWRtaW4=