apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: conference-app
type: Opaque
data:
  # conference_user (base64 encoded)
  POSTGRES_USER: Y29uZmVyZW5jZV91c2Vy
  # conference_pass (base64 encoded)
  POSTGRES_PASSWORD: Y29uZmVyZW5jZV9wYXNz
  # conference_db (base64 encoded)
  POSTGRES_DB: Y29uZmVyZW5jZV9kYg==
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: conference-app
type: Opaque
data:
  # admin (base64 encoded)
  GF_SECURITY_ADMIN_USER: YWRtaW4=
  # admin (base64 encoded)
  GF_SECURITY_ADMIN_PASSWORD: YWRtaW4=